# Generated by Django 5.2.1 on 2026-05-14 07:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('error', 'Error'), ('downtime', 'Downtime'), ('high_latency', 'High Latency')], max_length=12)),
                ('message', models.CharField(max_length=255)),
                ('alert_key', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=15)),
                ('trigger_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitoring.log')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.service')),
            ],
            options={
                'ordering': ['-last_triggered_at'],
                'indexes': [models.Index(fields=['service', 'status'], name='idx_alert_service_status'), models.Index(fields=['created_at'], name='idx_alert_created_at'), models.Index(fields=['service', 'alert_type'], name='idx_service_alert_type'), models.Index(fields=['service', 'severity'], name='idx_service_severity'), models.Index(condition=models.Q(('status', 'resolved'), _negated=True), fields=['service'], name='idx_active_alerts_per_service'), models.Index(condition=models.Q(('status', 'resolved'), _negated=True), fields=['service', 'last_triggered_at'], name='idx_active_ser_last_triggered'), models.Index(fields=['status', 'last_triggered_at'], name='idx_status_last_triggered')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'resolved'), _negated=True), fields=('service', 'alert_type', 'alert_key'), name='unique_active_alert_per_service_type_alert_key')],
            },
        ),
    ]
