# Generated by Django 5.2.1 on 2026-06-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='resolution_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
