"""
Django settings for ai_ops project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import environ
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent.parent

env = environ.Env()


settings_module = os.environ.get(
    "DJANGO_SETTINGS_MODULE",
    "ai_ops.settings.dev",
)

if settings_module.endswith(".prod"):
    environ.Env.read_env(BASE_DIR / ".env.prod")
else:
    environ.Env.read_env(BASE_DIR / ".env.dev")





# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = env('SECRET_KEY')



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'monitoring.apps.MonitoringConfig',
    'alerts.apps.AlertsConfig',
    'accounts.apps.AccountsConfig',
    'rest_framework',
    'rest_framework_simplejwt',
    'django.contrib.sites',
    'django_filters',
    'drf_spectacular',
    'anymail',
    'django_extensions',
    'django_celery_beat',


    # Allauth apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]


AUTHENTICATION_BACKENDS = [

    # default django auth
    "django.contrib.auth.backends.ModelBackend",

    # allauth backend
    "allauth.account.auth_backends.AuthenticationBackend",
]

# allauth settings
ACCOUNT_LOGIN_METHODS = {"email"}

ACCOUNT_USER_MODEL_USERNAME_FIELD = None

ACCOUNT_EMAIL_VERIFICATION = "mandatory"


ACCOUNT_SIGNUP_FIELDS = [
    "email*",
    "password1*",
    "password2*",
]


# Social account settings
SOCIALACCOUNT_AUTO_SIGNUP = True

SOCIALACCOUNT_LOGIN_ON_GET = True

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": env("GOOGLE_CLIENT_ID"),
            "secret": env("GOOGLE_CLIENT_SECRET"),
            "key": "",
        },
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    }
}

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',

    # REQUIRED FOR ALLAUTH
    'allauth.account.middleware.AccountMiddleware',


    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ai_ops.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [
            BASE_DIR / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "django.template.context_processors.debug",
            ],
        },
    },
]

WSGI_APPLICATION = 'ai_ops.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME', default='postgres'),
        'USER': env('DB_USER', default='postgres'),
        'PASSWORD': env('DB_PASSWORD', default=''),
        'HOST': env('DB_HOST', default='localhost'),
        'PORT': env('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
    "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    "OPTIONS": {
        "min_length": 8,
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


AUTH_USER_MODEL = 'accounts.User'



REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',


    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],

    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],

    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/day",
    },
    # Permissions
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
        # 'rest_framework.permissions.AllowAny',
    ],

}






SPECTACULAR_SETTINGS = {

    'TITLE': 'AI Ops Monitoring API',

    'DESCRIPTION': (
        'Production-grade monitoring and alerting platform API. '
        'Provides log ingestion, alert management, filtering, '
        'pagination, and monitoring operations.'
        'Features:'
        ' - Log ingestion'
        ' - Alert generation'
        ' - Alert lifecycle management'
        ' - Filtering'
        ' - Cursor pagination'
        ' - Incident resolution workflows'
    ),

    'VERSION': '1.0.0',

    'SERVE_INCLUDE_SCHEMA': False,


    'TAGS': [
        {
            'name': 'Logs',
            'description': 'Monitoring log operations',
        },
        {
            'name': 'Alerts',
            'description': 'Alert management operations',
        },
    ],
}



CELERY_BROKER_URL = env("CELERY_BROKER_URL")

CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND")

CELERY_ACCEPT_CONTENT = ["json"]

CELERY_TASK_SERIALIZER = "json"

CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = TIME_ZONE


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "accounts-cleanup": {
        "task": "accounts.tasks.cleanup_accounts",
        "schedule": crontab(minute=0),          # Every hour
    },
    "monitoring-cleanup": {
        "task": "monitoring.tasks.cleanup_monitoring",
        "schedule": crontab(hour=3, minute=0),  # Every day at 3 AM
    },
    "alerts-cleanup": {
        "task": "alerts.cleanup",
        "schedule": crontab(hour=4, minute=0),  # Every day at 4 AM
    },
}




# Testing Celery Beat schedule for development (every minute)
# from celery.schedules import crontab

# CELERY_BEAT_SCHEDULE = {
#     "accounts-cleanup": {
#         "task": "accounts.tasks.cleanup_accounts",
#         "schedule": crontab(),   # every minute
#     },
#     "monitoring-cleanup": {
#         "task": "monitoring.tasks.cleanup_monitoring",
#         "schedule": crontab(),   # every minute
#     },
#     "alerts-cleanup": {
#         "task": "alerts.cleanup",
#         "schedule": crontab(),   # every minute
#     },
# }






LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "standard": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },

    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },

    "loggers": {
        # Django logs
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },

        # Your application logs
        "ai_ops": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },

        "monitoring": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },

        "alerts": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}



CELERY_TASK_SOFT_TIME_LIMIT = 300
CELERY_TASK_TIME_LIMIT = 600



EMAIL_PROVIDER = env("EMAIL_PROVIDER")
EMAIL_BACKEND = env("EMAIL_BACKEND")
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env.int("EMAIL_PORT")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS")
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")
ALERT_EMAIL_RECIPIENTS = env.list("ALERT_EMAIL_RECIPIENTS")

FRONTEND_URL = env("FRONTEND_URL", default="http://localhost:3000")
BACKEND_URL = env("BACKEND_URL", default="http://localhost:8000")



EMAIL_NOTIFICATIONS_ENABLED = env.bool(
    "EMAIL_NOTIFICATIONS_ENABLED",
    default=True,
)

SLACK_NOTIFICATIONS_ENABLED = env.bool(
    "SLACK_NOTIFICATIONS_ENABLED",
    default=False,
)



# SimpleJWT (IMPORTANT)
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),

    "AUTH_HEADER_TYPES": ("Bearer",),

    "ALGORITHM": "HS256",

    "SIGNING_KEY": SECRET_KEY,
}



GOOGLE_CLIENT_ID = env("GOOGLE_CLIENT_ID")