from drf_spectacular.utils import (
    extend_schema,
    OpenApiExample,
    OpenApiParameter,
)

from alerts.serializers.alert_serializer import (
    AlertWriteSerializer,
    AlertReadSerializer,
    AlertResolveSerializer,
)





list_alerts_schema = extend_schema(
    tags=['Alerts'],

    summary='List alerts',
    description=(
        'Retrieve paginated alerts with '
        'filtering and ordering support.'
    ),

    parameters=[
        OpenApiParameter(
            name='service',
            description='Filter alerts by service ID.',
            required=False,
            type=int,
        ),

        OpenApiParameter(
            name='status',
            description='Filter alerts by alert status.',
            required=False,
            type=str,
        ),

        OpenApiParameter(
            name='severity',
            description='Filter alerts by severity.',
            required=False,
            type=str,
        ),

        OpenApiParameter(
            name='alert_type',
            description='Filter alerts by alert type.',
            required=False,
            type=str,
        ),

        OpenApiParameter(
            name='created_after',
            description='Return alerts created after this datetime.',
            required=False,
            type=str,
        ),

        OpenApiParameter(
            name='created_before',
            description='Return alerts created before this datetime.',
            required=False,
            type=str,
        ),

        OpenApiParameter(
            name='last_triggered_after',
            description='Return alerts triggered after this datetime.',
            required=False,
            type=str,
        ),

        OpenApiParameter(
            name='last_triggered_before',
            description='Return alerts triggered before this datetime.',
            required=False,
            type=str,
        ),

        OpenApiParameter(
            name='ordering',
            description=(
                'Order results by created_at, severity, '
                'trigger_count, or last_triggered_at. '
                'Use "-" for descending order.'
            ),
            required=False,
            type=str,
        ),
    ],

    examples=[
        OpenApiExample(
            'Filter By Status',
            description='Retrieve only open alerts.',
            value={
                'url': '/api/v1/alerts/?status=open'
            },
            request_only=True,
        ),

        OpenApiExample(
            'Filter By Severity',
            description='Retrieve only critical alerts.',
            value={
                'url': '/api/v1/alerts/?severity=critical'
            },
            request_only=True,
        ),

        OpenApiExample(
            'Filter By Service',
            description='Retrieve alerts for a specific service.',
            value={
                'url': '/api/v1/alerts/?service=1'
            },
            request_only=True,
        ),

        OpenApiExample(
            'Ordering Example',
            description='Order alerts by trigger count.',
            value={
                'url': '/api/v1/alerts/?ordering=-trigger_count'
            },
            request_only=True,
        ),
    ]
)





create_alert_schema = extend_schema(
    tags=['Alerts'],

    summary='Create alert',
    description=(
        'Create a new alert. '
        'Currently used for testing and QA workflows. '
        'In production alerts should be generated by the alert engine.'
    ),

    request=AlertWriteSerializer,

    responses={
        201: AlertReadSerializer,
    },

    examples=[
        OpenApiExample(
            'Error Alert Example',
            description='Database error alert.',
            value={
                'service': 1,
                'alert_type': 'error',
                'alert_key': 'error:1',
                'severity': 'high',
                'status': 'open',
                'message': 'Database connection failed'
            },
            request_only=True,
        ),

        OpenApiExample(
            'Downtime Alert Example',
            description='Service downtime alert.',
            value={
                'service': 1,
                'alert_type': 'downtime',
                'alert_key': 'downtime:1',
                'severity': 'critical',
                'status': 'open',
                'message': 'Service is unavailable'
            },
            request_only=True,
        ),

        OpenApiExample(
            'Validation Error Example',
            description='Invalid alert type.',
            value={
                'alert_type': [
                    'Invalid alert type.'
                ]
            },
            response_only=True,
            status_codes=['400'],
        ),
    ]
)





retrieve_alert_schema = extend_schema(
    tags=['Alerts'],

    summary='Retrieve single alert',

    description=(
        'Retrieve a single alert by ID.'
    ),

    responses={
        200: AlertReadSerializer,
    },

    examples=[
        OpenApiExample(
            'Single Alert Response',
            description='Example alert response.',
            value={
                'id': 1,
                'service': 1,
                'service_name': 'Auth Service',
                'alert_type': 'error',
                'message': 'Database connection failed',
                'severity': 'high',
                'status': 'open',
                'trigger_count': 3,
                'created_at': '2026-06-01T10:00:00Z',
                'last_triggered_at': '2026-06-01T10:15:00Z',
                'resolved_at': None
            },
            response_only=True,
        ),
    ]
)





resolve_alert_schema = extend_schema(
    tags=['Alerts'],

    summary='Resolve alert',

    description=(
        'Resolve an existing alert. '
        'This is a workflow action and not a generic update operation.'
    ),

    request=AlertResolveSerializer,

    responses={
        200: AlertReadSerializer,
    },

    examples=[
        OpenApiExample(
            'Resolve Alert Request',
            description='Resolve an alert with a resolution note.',
            value={
                'status': 'resolved',
                'resolution_note': 'Issue fixed after database restart.'
            },
            request_only=True,
        ),

        OpenApiExample(
            'Resolved Alert Response',
            description='Successfully resolved alert.',
            value={
                'id': 1,
                'service': 1,
                'service_name': 'Auth Service',
                'alert_type': 'error',
                'message': 'Database connection failed',
                'severity': 'high',
                'status': 'resolved',
                'trigger_count': 3,
                'created_at': '2026-06-01T10:00:00Z',
                'last_triggered_at': '2026-06-01T10:15:00Z',
                'resolved_at': '2026-06-01T10:20:00Z',
                'resolution_note': 'Issue fixed after database restart.'
            },
            response_only=True,
        ),

        OpenApiExample(
            'Validation Error Example',
            description='Resolution note missing.',
            value={
                'resolution_note': [
                    'Resolution note is required.'
                ]
            },
            response_only=True,
            status_codes=['400'],
        ),
    ]
)